"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.alternativeRouter = void 0;
const express_1 = require("express");
const alternative_controller_1 = require("../controller/alternative.controller");
const alternativeRouter = (0, express_1.Router)();
exports.alternativeRouter = alternativeRouter;
const alternativeController = new alternative_controller_1.AlternativeController();
alternativeRouter.post("/", alternativeController.register);
alternativeRouter.get("/", alternativeController.search);
alternativeRouter.put("/", alternativeController.update);
alternativeRouter.delete("/", alternativeController.remove);
